### ISSUE TITLE
Discussion & Vote: Describing State in Config

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#22]
A user wants to quickly define pattern states and their options for Pattern Lab. 

---

After looking through the docs the current implementation of pattern states is a bit awkward and indirect from a customization perspective. To implement a color for a state someone must edit a CSS file. Which one? Not sure there's a great choice. There's also no way to give a default state to all the things. I'd like to propose that we expand the pattern state configuration. From a PHP perspective if we expand this to a config then developers would have many hooks for defining pattern state (e.g. from a StarterKit or an Edition).
## System Input: Configuration

The current configuration in PHP is an array that simply lists pattern states in order of inheritance. A pattern state is added as a class in the output of the front-end. An example:

```
patternStates:
    - inprogress
    - inreview
    - complete
```

A new configuration would continue to be an array of pattern states in order of inheritance but each pattern state could have an OPTIONAL array of attributes. This would maintain backwards compatibility because we could check the pattern state value. If it's a string it's the old format or it should just be handled as a class name. If it's an array save the attributes and use the key as the class name. An example:

```
patternStates:
    - inprogress:
       - title: In Progress
         description: This is a description
         color: #444
         default: true
    - inreview:
        - title: In Review
          description: This is a description
          color: #555
    - complete:
        - title: Complete
          description: This is a description
          color: #666
```

I'm not sure if `title` or `description` would really find their way into the front-end but better to build them in now. `title` tag on pattern state-related link maybe?
## In System Use

If any state sets `default` to `true` then that state is the base from which all pattern state inheritance works if a pattern state isn't explicitly defined for a pattern. Currently we explicitly define it using `@state` but will be switching to `state: inprogress` in the `*.md` files.
## System Output

For the most part this is the same as it is currently. Patterns will have a state. Otherwise the configuration option `patternStates` could be passed whole to the front-end and `styleguidekit-assets-default` could check for it and build styles/tags as appropriate with the template.

The timeline for this feature is not critical.

Tagging spec-enhacement, core and front-end/shared because it affects an input to Pattern Lab and an output to `styleguidekit-assets-default`.

This vote will close at  9PM EST on July 22 or once two of the voting members have voted yay or nay.

/cc @pattern-lab/voting-members
